### ISSUE TITLE
Saving cover art in folder

### ISSUE THREAD

**Issue by FunkyFlapjacks** [Otiel/BandcampDownloader#15]
If you choose to save the cover art in folder it gets stuck at "Computing size for album X"

**Comment by Otiel** [comment]
My bad, lack of testing from my part before pushing the previous release. This should be fixed in the [release I've just posted](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.1.6.1). I'm closing this for now, let me now if you get any problem with the new version.

**Comment by deadmans96** [comment]
i still see this bug in the latest version 0.6.1 , if it's not make any bother to you , make a small modification on Make automatic folder for every album in this format ( Artist name - Album name ) BTW
